version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=ip-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  api:
    container_name: ip-lookup
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - .env
    links:
      - db